version: '2'

# Some Services to make local development easy
services:
  # External Services
  postgres:
    image: "postgres:9.6-alpine"
    ports:
      - "5434:5432"
    restart: always

  ngrok:
    image: "wernight/ngrok"
    ports:
      - "4040:4040"
    command: "ngrok http localhost:5000"